# Introduction to TensorFlow

> TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries, and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML-powered applications.   
[Official website](https://www.tensorflow.org/)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1200px-TensorFlowLogo.svg.png)

#### What is TensorFlow?

TensorFlow is the most popular library for training **Neural Networks**. In its core, however, TensorFlow is nothing more than a symbolic math library. What it does is it registers mathematical operations in what is known as a computation graph and executes them. The flow of data (which are stored in tensors) through the graph is what gives this library its name.

#### Implementation details

TensorFlow's most basic operations are essentially written in C++ and CUDA for GPU computations. The most popular way, however, to interact with the library is through its Python API, which is what we'll be learning

#### Tutorial 

The present tutorial is not meant to be a quick-start guide for TensorFlow, rather an in-depth guide to its functionalities. 

In this first lesson we'll see the main data type introduced in TensorFlow, as well as some of its **lowest level** opertions. These draw many similarities to [NumPy](https://numpy.org/). 

This tutorial will follow TensorFlow versions greater than 2, so no placeholders, sessions and name scopes.

Let's begin by confirming that TensorFlow is indeed installed and that we are running a version greater than 2.

In [0]:
# !pip install --upgrade tensorflow
import numpy as np

import tensorflow as tf
tf.__version__

## Basic data types

TensorFlow's basic data type is called a **tensor**. A [tensor](https://en.wikipedia.org/wiki/Tensor) in mathematics is essentially an object with more than $2$ dimensions. We've seen this concept before, but with a [different name](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.html). A tensor can have as many dimensions as we wish; One with $0$ dimensions can be called a scalar, with $1$ dimensions it is a vector and $2$ dimensions make it a matrix.

From a data structure point of view, TensorFlow's tensors are very much like numpy's ndarrays. The main differences are that tensors are much harder to work with, as they lack much of the functionality of numpy arrays (built-in methods, seamlessly working with core python functions, etc.) and the fact that they can be used for TensorFlow operations (where as numpy arrays can't).

There are two main tensor types, a Variable and a constant. The most important difference between the two are that the latter is immutable.

In [2]:
a = tf.constant([1, 2, 3, 4, 5])
b = tf.Variable([4, 5, 6, 7, 8])
print(a), print(b)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([4, 5, 6, 7, 8], dtype=int32)>


(None, None)

TensorFlow has its [own datatypes](https://www.tensorflow.org/api_docs/python/tf/dtypes), most of which should be very familiar. We can select the data type of any tensor duting instantiation.

In [0]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
a

It is also possible to change the dtype of a tensor by casting it to another. 

In [0]:
print(a.dtype)
r = tf.cast(r, tf.int64)
print(a.dtype)

Another way to create a tensor is to initialize it from an array or any other python iterable (list, typle, etc.).

In [3]:
arr = np.arange(9).reshape((3, 3))
t1 = tf.convert_to_tensor(arr)
t2 = tf.convert_to_tensor(arr.T)
t2

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>

Two other ways to initialize tensors are [`tf.zeros`](https://www.tensorflow.org/api_docs/python/tf/zeros) and [`tf.ones`](https://www.tensorflow.org/api_docs/python/tf/ones), which create tensors containing $0$s and $1$s respectively, with the given shape. These mimic [`numpy.zeros`](https://numpy.org/doc/1.18/reference/generated/numpy.zeros.html) and [`numpy.ones`](https://numpy.org/doc/1.18/reference/generated/numpy.ones.html).

In [4]:
z = tf.zeros((3, 4, 2), dtype=tf.float32)
z

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

### Basic arithmetic operations

Most common operations between tensors work with python's built-in operators. 

Note that all of these operations are performed **elementwise**.

In [5]:
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 ** t2)

tf.Tensor(
[[ 0  4  8]
 [ 4  8 12]
 [ 8 12 16]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[ 0  3 12]
 [ 3 16 35]
 [12 35 64]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[       nan 0.33333333 0.33333333]
 [3.         1.         0.71428571]
 [3.         1.4        1.        ]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[       1        1       64]
 [       3      256    78125]
 [      36    16807 16777216]], shape=(3, 3), dtype=int64)


Chaining operations is also possible.

In [6]:
r = (t1 - t2) ** 2
r

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 0,  4, 16],
       [ 4,  0,  4],
       [16,  4,  0]])>

To convert a tensor to a numpy array we can just use their built-in mehtod `.numpy()`.

In [7]:
arr_r = r.numpy()
arr_r

array([[ 0,  4, 16],
       [ 4,  0,  4],
       [16,  4,  0]])

### Comparisons

As in all logical comparisons, the outcomes here are boolean variable. The comparisons themselves work like in numpy: **elementwise**. 

In [9]:
print('Equal:')
print(t1 == t2)

print('\nUnequal:')
print(t1 != t2)

print('\nGreater:')
print(t1 > t2)

print('\nLess:')
print(t1 < t2)

print('\nGreater or equal:')
print(t1 >= t2)

print('\nLess or equal:')
print(t1 <= t2)

Equal:
tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)

Unequal:
tf.Tensor(
[[False  True  True]
 [ True False  True]
 [ True  True False]], shape=(3, 3), dtype=bool)

Greater:
tf.Tensor(
[[False False False]
 [ True False False]
 [ True  True False]], shape=(3, 3), dtype=bool)

Less:
tf.Tensor(
[[False  True  True]
 [False False  True]
 [False False False]], shape=(3, 3), dtype=bool)

Greater or equal:
tf.Tensor(
[[ True False False]
 [ True  True False]
 [ True  True  True]], shape=(3, 3), dtype=bool)

Less or equal:
tf.Tensor(
[[ True  True  True]
 [False  True  True]
 [False False  True]], shape=(3, 3), dtype=bool)


## Random

[This module](https://www.tensorflow.org/api_docs/python/tf/random) is like [`numpy.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html), containing functions that involve randomness.

Most commonly we'll be sampling data from distributions: 


In [15]:
print(tf.random.uniform((4,)))  # draws samples from a uniform distribution

print(tf.random.normal((4,)))  # draws samples from a normal distribution

print(tf.random.truncated_normal((4,)))  # draws samples from a truncated normal distribution

tf.Tensor([0.00412071 0.40792263 0.65332854 0.1388886 ], shape=(4,), dtype=float32)
tf.Tensor([-0.3198804   1.3575249  -0.15776916  0.5804112 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.80348307 -0.36864722 -0.7620199  -0.3464329 ], shape=(4,), dtype=float32)


Another important function is `tf.random.shuffle()`.

In [18]:
c = tf.constant([1, 2, 3, 4])
c = tf.random.shuffle(c)  # Note that unlike numpy's shuffle, this doens't change the 
                          # tensor inplace. Even if it worked that way the tensor
                          # is immutable, so we'd get an error. 
c

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 1, 3, 4], dtype=int32)>

For repeatability, TensorFlow uses its own random seed. 

In [16]:
tf.random.set_seed(13)
print(tf.random.uniform((4,)))

tf.Tensor([0.5983684  0.07627809 0.34005308 0.9105623 ], shape=(4,), dtype=float32)


This works a bit stranger than expected, because TensorFlow generators keep their own counter so that they won't repeat the same numbers if they are called twice.  More details on how it works can be found in the [function's documentation](https://www.tensorflow.org/api_docs/python/tf/random/set_seed).

## Math operations

As we saw previously, the basic math operations between tensors (sum, prod, etc.) work with python's default operators (`+`, `*`, etc.). TensorFlow, offers a lot more in under the [`tensorflow.math`](https://www.tensorflow.org/api_docs/python/tf/math) module. Some examples are:

In [31]:
t = tf.convert_to_tensor(np.random.rand(16) * 10 - 5)

print('Absolute:')
print(tf.math.abs(t))

print('\nRound:')
print(tf.math.round(t))

print('\nCeiling:')
print(tf.math.ceil(t))

print('\nSign:')
print(tf.math.sign(t))

print('\nSquare root:')
print(tf.math.sqrt(t))

print('\nCount nonzero elements:')
c = tf.constant([0, 1, 1, 0, 0, 0, 1, 0, 1])
print(tf.math.count_nonzero(c))

print('\nNatural Logarithm:')
c = tf.constant([0, 1, 2, 3, 4], dtype=tf.float32)
print(tf.math.log(c))

Absolute:
tf.Tensor(
[0.95614473 3.54541168 1.97925459 2.79243016 3.41595829 3.32250725
 3.12813022 4.20335484 1.38051089 4.23267088 1.61225906 0.77238135
 4.03042373 4.70960668 1.34142106 1.14714063], shape=(16,), dtype=float64)

Round:
tf.Tensor([-1. -4. -2. -3.  3. -3. -3. -4. -1.  4. -2. -1. -4.  5. -1. -1.], shape=(16,), dtype=float64)

Ceiling:
tf.Tensor([-0. -3. -1. -2.  4. -3. -3. -4. -1.  5. -1. -0. -4.  5. -1. -1.], shape=(16,), dtype=float64)

Sign:
tf.Tensor([-1. -1. -1. -1.  1. -1. -1. -1. -1.  1. -1. -1. -1.  1. -1. -1.], shape=(16,), dtype=float64)

Count nonzero elements:
tf.Tensor(4, shape=(), dtype=int64)

Natural Logarithm:
tf.Tensor([     -inf 0.        0.6931472 1.0986123 1.3862944], shape=(5,), dtype=float32)


### Trigonometric functions

In [29]:
t = tf.constant([-0.5, 0, 0.5, 1, 1.5], dtype=tf.float32)
print('Original:')
print(t)

print('\nSine:')
print(tf.math.sin(t))

print('\nCosine:')
print(tf.math.cos(t))

print('\nTangent:')
print(tf.math.tan(t))

print('\nHyperbolic Sine:')
print(tf.math.sinh(t))

print('\nHyperbolic Cosine:')
print(tf.math.cosh(t))

print('\nHyperbolic Tangent:')
print(tf.math.tanh(t))

print('\nInverse Sine (arcsin):')
print(tf.math.asin(t))

print('\nInverse Cosine (arccos):')
print(tf.math.acos(t))

print('\nInverse Tangent (arctan):')
print(tf.math.atan(t))


Original:
tf.Tensor([-0.5  0.   0.5  1.   1.5], shape=(5,), dtype=float32)

Sine:
tf.Tensor([-0.47942555  0.          0.47942555  0.841471    0.997495  ], shape=(5,), dtype=float32)

Cosine:
tf.Tensor([0.87758255 1.         0.87758255 0.5403023  0.0707372 ], shape=(5,), dtype=float32)

Tangent:
tf.Tensor([-0.5463025  0.         0.5463025  1.5574079 14.10142  ], shape=(5,), dtype=float32)

Hyperbolic Sine:
tf.Tensor([-0.5210953  0.         0.5210953  1.1752012  2.1292794], shape=(5,), dtype=float32)

Hyperbolic Cosine:
tf.Tensor([1.127626  1.        1.127626  1.5430806 2.3524096], shape=(5,), dtype=float32)

Hyperbolic Tangent:
tf.Tensor([-0.46211714  0.          0.46211714  0.7615942   0.90514827], shape=(5,), dtype=float32)

Inverse Sine (arcsin):
tf.Tensor([-0.5235988  0.         0.5235988  1.5707964        nan], shape=(5,), dtype=float32)

Inverse Cosine (arccos):
tf.Tensor([2.0943952 1.5707964 1.0471976 0.              nan], shape=(5,), dtype=float32)

Inverse Tangent (arctan):
tf.

### Check for `nan` or `inf`

In [30]:
t = tf.convert_to_tensor(np.array([1, np.nan, 2, np.inf, 3, -np.inf, 4]))
print('Original:')
print(t)

print('\nIs finite?')
print(tf.math.is_finite(t))

print('\nIs nan?')
print(tf.math.is_nan(t))

print('\nIs infinite?')
print(tf.math.is_inf(t))

Original:
tf.Tensor([  1.  nan   2.  inf   3. -inf   4.], shape=(7,), dtype=float64)

Is finite?
tf.Tensor([ True False  True False  True False  True], shape=(7,), dtype=bool)

Is nan?
tf.Tensor([False  True False False False False False], shape=(7,), dtype=bool)

Is infinite?
tf.Tensor([False False False  True False  True False], shape=(7,), dtype=bool)


### Reduce operations

All operations we've seen up till now are elementwise (i.e. they don't affect the dimensions of the input tensors).

Reduce opeations, on the other hand **reduce** the dimensions of their input. The most common example of a reduce operation is `max()`; this function takes $N$ items as its input and returns just $1$, i.e. the max.

In [41]:
print('Original:')
print(c)

print('\nMin:')
print(tf.math.reduce_min(c))

print('\nMax:')
print(tf.math.reduce_max(c))

print('\nMean:')
print(tf.math.reduce_mean(c))

print('\nSum:')
print(tf.math.reduce_sum(c))

print('\nProduct:')
print(tf.math.reduce_prod(c))

Original:
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)

Min:
tf.Tensor(0.0, shape=(), dtype=float32)

Max:
tf.Tensor(4.0, shape=(), dtype=float32)

Mean:
tf.Tensor(2.0, shape=(), dtype=float32)

Sum:
tf.Tensor(10.0, shape=(), dtype=float32)

Product:
tf.Tensor(0.0, shape=(), dtype=float32)


Two other very useful reduce operations are `any` and `all`:

In [42]:
c1 = tf.constant([True, True, True, True])
c2 = tf.constant([True, False, False, False])
c3 = tf.constant([False, False, False, False])

print('c1:')
print(c1)
print('c2:')
print(c2)
print('c3:')
print(c3)

print('\nAny (c1, c2, c3):')
print(tf.math.reduce_any(c1))
print(tf.math.reduce_any(c2))
print(tf.math.reduce_any(c3))

print('\nAll (c1, c2, c3):')
print(tf.math.reduce_all(c1))
print(tf.math.reduce_all(c2))
print(tf.math.reduce_all(c3))

c1:
tf.Tensor([ True  True  True  True], shape=(4,), dtype=bool)
c2:
tf.Tensor([ True False False False], shape=(4,), dtype=bool)
c3:
tf.Tensor([False False False False], shape=(4,), dtype=bool)

Any (c1, c2, c3):
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(False, shape=(), dtype=bool)

All (c1, c2, c3):
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor(False, shape=(), dtype=bool)


### Segmentation Operations

These operations perform computations on tensor **segments**. The available operations are [min](https://www.tensorflow.org/api_docs/python/tf/math/segment_min), [max](https://www.tensorflow.org/api_docs/python/tf/math/segment_max), [mean](https://www.tensorflow.org/api_docs/python/tf/math/segment_mean), [sum](https://www.tensorflow.org/api_docs/python/tf/math/segment_sum) and [prod](https://www.tensorflow.org/api_docs/python/tf/math/segment_prod).

For example

```python
data = tf.constant([5, 1, 7, 2, 3, 4, 1, 3])
segmentation_ids = tf.constant([0, 0, 0, 1, 2, 2, 3, 3])
tf.math.segment_sum(data, segmentation_ids)
```

![](https://www.tensorflow.org/images/SegmentSum.png)


On N-dimensional tensors, the `segmentation_ids` correspond to the first dimension of the input tensor.

In [16]:
c = tf.constant([[1, 5, 3, 7], [4, 2, 8, 6], [-1, -5, -3, -7], [-2, -4, 0, -6]])
c

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  5,  3,  7],
       [ 4,  2,  8,  6],
       [-1, -5, -3, -7],
       [-2, -4,  0, -6]], dtype=int32)>

From the tensor above we want to find the max element per column. However, we want to take into account the first two rows **separately** from last two (i.e. one max per column for rows 1 and 2 and one max per column for rows 3 and 4).

In [17]:
tf.math.segment_max(c, tf.constant([0, 0, 1, 1]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  8,  7],
       [-1, -4,  0, -6]], dtype=int32)>

Note that this operation essentially segments a tensor into some parts and efficiently performs a computation on each segment. These segments, however **need to be sorted** and cannot be shuffled (i.e. the second segment must start after the first has ended). For example an arrangement like this is invalid:

```python
tf.math.segment_max(c, tf.constant([0, 1, 0, 1]))
```

If we want the above we will have to use one of the **unsorted_segment** operations, namely:




In [20]:
tf.math.unsorted_segment_max(c, tf.constant([0, 1, 0, 1]), num_segments=2)  # the num_segments argument is necessary

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 5, 3, 7],
       [4, 2, 8, 6]], dtype=int32)>

### Logical operations

The final category of functions we'll see are logical ones. These perform operations **between boolean values**.

In [34]:
b1 = tf.convert_to_tensor([True, False, True, False])
b2 = tf.convert_to_tensor([True, True, False, False])

print('B1:')
print(b1)

print('\nB2:')
print(b2)

print('\nB1 and B2:')
print(tf.math.logical_and(b1, b2))

print('\nB1 or B2:')
print(tf.math.logical_or(b1, b2))

print('\nnot B1:')
print(tf.math.logical_not(b1))

B1:
tf.Tensor([ True False  True False], shape=(4,), dtype=bool)

B2:
tf.Tensor([ True  True False False], shape=(4,), dtype=bool)

B1 and B2:
tf.Tensor([ True False False False], shape=(4,), dtype=bool)

B1 or B2:
tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)

not B1:
tf.Tensor([False  True False  True], shape=(4,), dtype=bool)


## Linear Algebra

[`tensorflow.linalg`](https://www.tensorflow.org/api_docs/python/tf/linalg) is another module focucing on linear algebra operations. The most common of these are: 

In [52]:
r1 = tf.cast(r, dtype=tf.float32)

print('\nEigenvalue decomposition:')
e, v = tf.linalg.eig(r1)
print(e)  # eigenvalues
print(v)  # eigenvectors

print('\nMatrix Exponential:')
print(tf.linalg.expm(r1))

print('\nInverse:')
print(tf.linalg.inv(r1))

print('\nMatrix Norm (2nd order):')
print(tf.linalg.norm(r1))  # this has a parameter ord to control the order of the norm

print('\nTranspose:')
r2 = tf.linalg.matrix_transpose(r1)
print(r2)

print('\nMatrix multiplication:')
print(tf.linalg.matmul(r1, r2))


Eigenvalue decomposition:
tf.Tensor([ -1.7979586+0.j -15.999998 +0.j  17.797955 +0.j], shape=(3,), dtype=complex64)
tf.Tensor(
[[ 2.1418646e-01+0.j  7.0710689e-01+0.j  6.7388737e-01+0.j]
 [-9.5302063e-01+0.j  2.0383558e-08+0.j  3.0290541e-01+0.j]
 [ 2.1418653e-01+0.j -7.0710671e-01+0.j  6.7388731e-01+0.j]], shape=(3, 3), dtype=complex64)

Matrix Exponential:
tf.Tensor(
[[24363084. 10950958. 24363084.]
 [10950956.  4922343. 10950956.]
 [24363084. 10950956. 24363082.]], shape=(3, 3), dtype=float32)

Inverse:
tf.Tensor(
[[-0.03125  0.125    0.03125]
 [ 0.125   -0.5      0.125  ]
 [ 0.03125  0.125   -0.03125]], shape=(3, 3), dtype=float32)

Matrix Norm (2nd order):
tf.Tensor(24.0, shape=(), dtype=float32)

Transpose:
tf.Tensor(
[[ 0.  4. 16.]
 [ 4.  0.  4.]
 [16.  4.  0.]], shape=(3, 3), dtype=float32)

Matrix multiplication:
tf.Tensor(
[[272.  64.  16.]
 [ 64.  32.  64.]
 [ 16.  64. 272.]], shape=(3, 3), dtype=float32)


## Important note on tensorflow modules:

The most common operations that are defined inside any of TensorFlow's modules have easily accessible aliases under `tensorflow`. 

For example, to compute the elementwise absolute values of a tensor `t` we can just write `tf.abs(t)` instead of `tf.math.abs(t)`.

It is important to note that these are **just aliases** and not different functions. This can be simply confirmed:

In [55]:
print(tf.abs is tf.math.abs)
print(tf.norm is tf.linalg.norm)

True
True


There has been a lot of effort made in TF2 to [clean up](https://www.tensorflow.org/guide/effective_tf2#api_cleanup) the `tensorflow` module, which was overbloated with aliases like these. For this reason I prefer using calling the functions from where they are defined and not their aliases (e.g. `tf.math.abs` instead of `tf.abs`). This, however, is simply a matter of preference.